---
ENABLE_LINTERS:
  - COPYPASTE_JSCPD
  - DOCKERFILE_HADOLINT
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SECRETLINT
  - REPOSITORY_SEMGREP
  - REPOSITORY_TRIVY
  - YAML_YAMLLINT
JSON_JSONLINT_ARGUMENTS: "--comments"
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: CHANGELOG.md # file is managed by standard-version
REPOSITORY_SEMGREP_RULESETS: ["p/ci", "p/python"]
