# mypy global options:

[tool.mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "moto"
ignore_missing_imports = true

# pytest

[tool.pytest.ini_options]
  addopts = [
    "-rA",
    "-v",
    "--cov",
    "--cov-config=pyproject.toml",
    "--cov-report=xml"
  ]
  testpaths = "tests"

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if TYPE_CHECKING:"
]

[tool.coverage.run]
  branch = false
  source = ["header_setter"]

# Pylint
[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = "logging-fstring-interpolation"