name: GitHub Actions Python
run-name: ${{ github.actor }} is triggering tests and linters
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: 'pipenv'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install -d
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint header_setter tests
    - name: Analysing the code with mypy
      run: |
        pipenv run mypy --install-types header_setter tests
    - name: Analysing the code with bandit
      run: |
        pipenv run bandit -r header_setter
    - name: Running unit tests
      run: |
        pipenv run pytest --cov header_setter --cov-report term